# -*- coding: utf-8 -*-
"""Internal Assesment 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RSc3G6FUG__el0bYp8n5wuJ2oP5JDynv
"""

# QN1
length = float(input('Enter the length of the rectangle:'))
width = float(input('Enter the width of the rectangle:'))

Area = length*width

print(f'The area of the rectange with length {length} and width {width} is:',Area)

# QN 2
Weight = float(input('Enter your weight in kgs:'))
Height = float(input('Enter your height in meters:'))

BMI = Weight/Height

print(f'The area of the rectange with Weight {Weight} in kg and Height {Height} in meters is:',round(BMI,2))

# QN 3
Student = {}
continue_1 = 'TRUE'
while continue_1 == 'TRUE':
    Student_name = input('Enter name of student')
    marks = input('Enter their marks').split(',')
    if Student_name not in Student:
        Student[Student_name] = marks
    continue_1 = input('Do you still want to continue, TRUE OR FALSE')
    if continue_1 == 'FALSE':
        break

print(Student)

# QN 4
users_age = int(input('Enter your age:'))

if users_age < 18:
    print('Minor')
elif users_age <60:
    print('Adult')
else:
    print('Senior')

# QN 5
for i in range(1,51):
    if i%2 == 0:
        print(i)

# QN 6
continue_1 = "TRUE"
password = "PasswordLV"
while continue_1 == "TRUE":
    user_password = input('Enter the password')
    if user_password != password:
        print('Enter the correct pasword')
    if user_password == password:
        print('You have finally entered the correct password')
        break
    continue_1 = input('Do you still want to continue TRUE/FALSE')

# QN 7
def average(n1,n2,n3,n4):
    average = (n1+n2+n3+n4)/4


    return average


# We can also find the average of the first n numbers
def average_consecutive(n):
    a = 0
    for i in range(1,n+1):
        a = a+i
    return a/n

average(5,6,7,8)

average_consecutive(10)

# QN 8
def count_vowels(word):
    vowels = 'AaEeIiOoUu'
    count = 0
    for i in range(len(word)):
        if word[i] in vowels:
            count = count + 1
    return count

count_vowels('Alphabet')

count_vowels('racecar')

# QN 9
import datetime as dt

current_date = dt.datetime.now()
print(current_date)

# QN 10
try:
    a = int(input('Enter first value'))
    b = int(input('Enter the second value'))
    print(a+b)
except ValueError:
    print('Non-numeric inputs not allowed')

# QN 11

try:
    a = int(input('Enter an integer value'))
    print(a)
except ValueError:
    print('The value cannot be a non integer')

# QN 12
def division_function(a,b):
    try:
        return b/a
    except ZeroDivisionError:
        print('Division by zero is not possible')

# QN 13
f = open('Python.txt','w')
f.writelines('Hello,Python!')

# QN 14
f = open('Python.txt','r')
f.readlines()

# QN 15
f = open('Python.txt','a')
f.writelines('Good to see you here')

f = open('Python.txt','r')
f.readlines()

